### ISSUE TITLE
Question about use of the website

### ISSUE THREAD

**Issue by whileNazaTrue** [magicwenli/league-fan#2]
Hello! I am developing a Discord Bot at the moment. I was wondering if you would allow me to use the site to get the images for a thumbnail in an embed, which would look like this.
![image](https://user-images.githubusercontent.com/84025828/179129828-c1b35ab3-d69b-4e42-844c-a084c563f2f9.png)

Sorry if this isn't the right channel to make a question like this, but I couldn't find anywhere else to contact you.

Thanks for your time.

**Comment by wesleyel** [comment]
Sorry for not replying in time, this project is free to use, you can do all you want with it!
