### ISSUE TITLE
Page have not updated anything

### ISSUE THREAD

**Issue by jusstleeaz** [magicwenli/league-fan#3]
Sir, the page has not been updated with any new assets. Still 12.14. Please fix, thank you!

**Comment by wesleyel** [comment]
Thank you for your feedback! I'll trying to figure it out.

**Comment by wesleyel** [comment]
Hi, jusstleeaz:

The [scheduled publish workflow](https://github.com/league-fan/league-fan-assets/actions/workflows/scheduled-publish.yml) is automatically disabled because of repo inactive for more than 60 days. I'v restarted it, should be fine now.

Thank you for your feedback, again!

magicwenli
